version: '3'

services:
  monapp:
    image: docker_django_tutorial
    ports:
      - 90:90
    build: .
    command: python3 manage.py runserver 0.0.0.0:90

  react:
    restart: always
    image: react-app
    build:
      context: ./margreact/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: npm start
